### ISSUE TITLE
FEniCS on Scientific Linux

### ISSUE THREAD

**Issue by xpqian** [Juanlu001/fenics-recipes#10]
I am trying to use conda to install FEniCS on Scientific Linux release 6.3.

When I tried FEniCS 1.5, it gave me error: "ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/xqian29/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/_ufc.so)".

When I tried to install FEniCS 1.4 with the command "conda install "fenics=1.4.0" mkl --channel https://conda.binstar.org/juanlu001/channel/fenics:1.4.0:centos", I got the following error:
"File "/home/xqian29/anaconda/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/xqian29/anaconda/lib/libslepc.so)".

Any idea to fix it?

Thanks,
Xiaoping.

**Comment by astrojuanlu** [comment]
Thanks for the bug report @xpqian. I will have to investigate it but this smells like a problem with the `slepc` package. I recall compiling it properly but I see a mismatch in the path of the library, would you please post the output of this commands?

```
conda info -a
source activate fenics27
conda list
source deactivate
conda list
```

**Comment by xpqian** [comment]
Thank you for your response. Here are the outputs of the commands.

[xqian29@aci-service-1 python]$ conda info -a
Current conda install:

```
         platform : linux-64
    conda version : 3.10.1
```

  conda-build version : 1.12.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/xqian29/anaconda  (writable)
  default environment : /home/xqian29/anaconda
     envs directories : /home/xqian29/anaconda/envs
        package cache : /home/xqian29/anaconda/pkgs
         channel URLs : https://conda.binstar.org/juanlu001/linux-64/
                        https://conda.binstar.org/juanlu001/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/xqian29/.condarc
    is foreign system : False

# conda environments:

#
fenics27                 /home/xqian29/anaconda/envs/fenics27
root                  \*  /home/xqian29/anaconda

sys.version: 2.7.9 |Anaconda 2.2.0 (64-bit)| (default...
sys.prefix: /home/xqian29/anaconda
sys.executable: /home/xqian29/anaconda/bin/python
conda location: /home/xqian29/anaconda/lib/python2.7/site-packages/conda
conda-build: /home/xqian29/anaconda/bin/conda-build
conda-convert: /home/xqian29/anaconda/bin/conda-convert
conda-develop: /home/xqian29/anaconda/bin/conda-develop
conda-env: /home/xqian29/anaconda/bin/conda-env
conda-index: /home/xqian29/anaconda/bin/conda-index
conda-inspect: /home/xqian29/anaconda/bin/conda-inspect
conda-metapackage: /home/xqian29/anaconda/bin/conda-metapackage
conda-pipbuild: /home/xqian29/anaconda/bin/conda-pipbuild
conda-server: /home/xqian29/anaconda/bin/conda-server
conda-skeleton: /home/xqian29/anaconda/bin/conda-skeleton
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: /home/xqian29/anaconda/lib:
PATH: /home/xqian29/anaconda/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/dell/srvadmin/bin:/home/xqian29/bin
PYTHONHOME: <not set>
PYTHONPATH: /home/xqian29/anaconda/lib/python2.7/site-packages:/home/xqian29/anaconda/lib/python2.7/site-packages:

License directories:
    /home/xqian29/.continuum
    /home/xqian29/anaconda/licenses
License files (license*.txt):
Package/feature end dates:
[xqian29@aci-service-1 python]$ source activate fenics27
discarding /home/xqian29/anaconda/bin from PATH
prepending /home/xqian29/anaconda/envs/fenics27/bin to PATH
(fenics27)[xqian29@aci-service-1 python]$ conda list

# packages in environment at /home/xqian29/anaconda/envs/fenics27:

#
abstract-rendering        0.5.1                     <pip>
argcomplete               0.8.4                     <pip>
astropy                   1.0.1                     <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.8.1                     <pip>
beautifulsoup4            4.3.2                     <pip>
binstar                   0.10.1                    <pip>
bitarray                  0.8.1                     <pip>
blaze                     0.7.3                     <pip>
blz                       0.6.2                     <pip>
bokeh                     0.8.1                     <pip>
boost                     1.55.0                        1
boto                      2.36.0                    <pip>
cdecimal                  2.3                       <pip>
certifi                   14.5.14                   <pip>
cffi                      0.9.2                     <pip>
clyent                    0.3.4                     <pip>
cmake                     3.0.1                         0
colorama                  0.3.3                     <pip>
conda                     3.10.1                    <pip>
conda-build               1.12.0                    <pip>
conda-env                 2.1.4                     <pip>
configobj                 5.0.6                     <pip>
cython                    0.22                      <pip>
cytoolz                   0.7.2                     <pip>
datashape                 0.4.4                     <pip>
decorator                 3.4.0                     <pip>
docutils                  0.12                      <pip>
dolfin                    1.4.0                    py27_2
eigen3                    3.2.1                         0
enum34                    1.0.4                     <pip>
fastcache                 1.0.2                     <pip>
fenics                    1.4.0                         1
ffc                       1.4.0                    py27_1
fiat                      1.4.0                    py27_1
flask                     0.10.1                    <pip>
fontconfig                2.11.1                        3
freetype                  2.5.2                         0
funcsigs                  0.4                       <pip>
futures                   2.2.0                     <pip>
gevent                    1.0.1                     <pip>
gevent-websocket          0.9.3                     <pip>
greenlet                  0.4.5                     <pip>
grin                      1.2.1                     <pip>
h5py                      2.4.0                     <pip>
hashdist                  0.3                       <pip>
instant                   1.4.0                    py27_1
ipython                   3.0.0                     <pip>
itsdangerous              0.24                      <pip>
jdcal                     1.0                       <pip>
jedi                      0.8.1                     <pip>
jinja2                    2.7.3                     <pip>
jsonschema                2.4.0                     <pip>
libpng                    1.5.13                        1
libxml2                   2.9.0                         0
llvmlite-0.2.2-1          gbcb15be                  <pip>
lxml                      3.4.2                     <pip>
markupsafe                0.23                      <pip>
matplotlib                1.4.3                     <pip>
mistune                   0.5.1                     <pip>
mkl                       11.1                np18py27_p3
mkl-rt                    11.1                         p0
mkl-service               1.0.0                   py27_p1
mock                      1.0.1                     <pip>
mpi4py                    1.3                      py27_0
mpich2                    1.4.1p1                       0
multipledispatch          0.4.7                     <pip>
networkx                  1.9.1                     <pip>
nltk                      3.0.2                     <pip>
nose                      1.3.4                     <pip>
numba                     0.17.0                    <pip>
numexpr                   2.3.1               np18py27_p0  [mkl]
numpy                     1.8.2                   py27_p0  [mkl]
odo                       0.3.1                     <pip>
openpyxl                  1.8.5                     <pip>
openssl                   1.0.1k                        1
pandas                    0.15.2                    <pip>
patsy                     0.3.0                     <pip>
pcre                      8.31                          0
pep8                      1.6.2                     <pip>
petsc                     3.4.5                    py27_1
petsc4py                  3.4                      py27_1
pillow                    2.7.0                     <pip>
pip                       6.1.1                    py27_0
ply                       3.4                      py27_0
psutil                    2.2.1                     <pip>
ptyprocess                0.4                       <pip>
py                        1.4.26                    <pip>
pyasn1                    0.1.7                     <pip>
pycosat                   0.6.1                     <pip>
pycparser                 2.10                      <pip>
pycrypto                  2.6.1                     <pip>
pycurl                    7.19.5.1                  <pip>
pyflakes                  0.8.1                     <pip>
pygments                  2.0.2                     <pip>
pyopenssl                 0.14                      <pip>
pyparsing                 2.0.3                     <pip>
pytest                    2.6.4                     <pip>
python                    2.7.9                         2
python-dateutil           2.4.1                     <pip>
pytz                      2015.2                    <pip>
pyyaml                    3.11                      <pip>
pyzmq                     14.5.0                    <pip>
qt                        4.8.6                         1
readline                  6.2                           2
redis                     2.10.3                    <pip>
requests                  2.6.0                     <pip>
rope                      0.9.4                     <pip>
runipy                    0.1.3                     <pip>
scientificpython          2.9.4                    py27_9
scikit-image              0.11.2                    <pip>
scikit-learn              0.15.0b1            np18py27_p0  [mkl]
scipy                     0.14.0              np18py27_p0  [mkl]
setuptools                15.0                     py27_0
six                       1.9.0                    py27_0
slepc                     3.4.4                    py27_2
sockjs-tornado            1.0.1                     <pip>
sphinx                    1.2.3                     <pip>
spyder                    2.3.4                     <pip>
sqlalchemy                0.9.9                     <pip>
sqlite                    3.8.4.1                       1
statsmodels               0.6.1                     <pip>
swig                      3.0.2                         0
sympy                     0.7.6                     <pip>
system                    5.8                           2
tables                    3.1.1                     <pip>
terminado                 0.5                       <pip>
theano                    0.6.0                     <pip>
tk                        8.5.18                        0
toolz                     0.7.1                     <pip>
tornado                   4.1                       <pip>
ufl                       1.4.0                    py27_1
ujson                     1.33                      <pip>
unicodecsv                0.9.4                     <pip>
vtk                       5.10.1                   py27_1
werkzeug                  0.10.1                    <pip>
xlrd                      0.9.3                     <pip>
xlsxwriter                0.6.7                     <pip>
xlwt                      0.7.5                     <pip>
zlib                      1.2.8                         0
(fenics27)[xqian29@aci-service-1 python]$ source deactivate
discarding /home/xqian29/anaconda/envs/fenics27/bin from PATH
[xqian29@aci-service-1 python]$ conda list

# packages in environment at /home/xqian29/anaconda:

#
_license                  1.1                      py27_0
abstract-rendering        0.5.1                np19py27_0
anaconda                  2.2.0                np19py27_0
argcomplete               0.8.4                    py27_0
astropy                   1.0.1                np19py27_0
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.8.1                np19py27_0
beautiful-soup            4.3.2                    py27_0
beautifulsoup4            4.3.2                     <pip>
binstar                   0.10.1                   py27_3
bitarray                  0.8.1                    py27_0
blaze                     0.7.3                     <pip>
blaze-core                0.7.3                np19py27_0
blz                       0.6.2                np19py27_0
bokeh                     0.8.1                np19py27_1
boost                     1.55.0                        1
boto                      2.36.0                   py27_0
cairo                     1.12.18                       1
cdecimal                  2.3                      py27_0
certifi                   14.05.14                 py27_0
cffi                      0.9.2                    py27_0
clyent                    0.3.4                    py27_0
cmake                     3.0.1                         0
colorama                  0.3.3                    py27_0
conda                     3.10.1                   py27_0
conda-build               1.12.0                   py27_0
conda-env                 2.1.4                    py27_0
configobj                 5.0.6                    py27_0
cryptography              0.8                      py27_0
curl                      7.38.0                        0
cython                    0.22                     py27_0
cytoolz                   0.7.2                    py27_0
datashape                 0.4.4                np19py27_1
decorator                 3.4.0                    py27_0
docutils                  0.12                     py27_0
dolfin                    1.4.0                    py27_2
dynd-python               0.6.5                np19py27_0
eigen3                    3.2.1                         0
enum34                    1.0.4                    py27_0
fastcache                 1.0.2                    py27_0
fenics                    1.4.0                         1
ffc                       1.4.0                    py27_1
fiat                      1.4.0                    py27_1
flask                     0.10.1                   py27_1
fontconfig                2.11.1                        3
freetype                  2.5.2                         0
funcsigs                  0.4                      py27_0
futures                   2.2.0                    py27_0
gevent                    1.0.1                    py27_0
gevent-websocket          0.9.3                    py27_0
greenlet                  0.4.5                    py27_0
grin                      1.2.1                    py27_1
h5py                      2.4.0                np19py27_0
hashdist                  0.3                       <pip>
hdf5                      1.8.14                        0
instant                   1.4.0                    py27_1
ipython                   3.0.0                    py27_0
ipython-notebook          3.0.0                    py27_1
ipython-qtconsole         3.0.0                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.0                      py27_0
jedi                      0.8.1                    py27_0
jinja2                    2.7.3                    py27_1
jpeg                      8d                            0
jsonschema                2.4.0                    py27_0
libdynd                   0.6.5                         0
libffi                    3.0.13                        0
libpng                    1.5.13                        1
libsodium                 0.4.5                         0
libtiff                   4.0.2                         1
libxml2                   2.9.0                         0
libxslt                   1.1.28                        0
llvmlite                  0.2.2                    py27_1
lxml                      3.4.2                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.4.3                np19py27_1
mistune                   0.5.1                    py27_0
mkl                       11.1                np18py27_p3
mkl-rt                    11.1                         p0
mkl-service               1.0.0                   py27_p1
mock                      1.0.1                    py27_0
mpi4py                    1.3                      py27_0
mpich2                    1.4.1p1                       0
multipledispatch          0.4.7                    py27_0
networkx                  1.9.1                    py27_0
nltk                      3.0.2                np19py27_0
nose                      1.3.4                    py27_1
numba                     0.17.0               np19py27_0
numexpr                   2.3.1               np18py27_p0  [mkl]
numpy                     1.8.2                   py27_p0  [mkl]
odo                       0.3.1                np19py27_0
openpyxl                  1.8.5                    py27_0
openssl                   1.0.1k                        1
pandas                    0.15.2               np19py27_1
patchelf                  0.6                           0
patsy                     0.3.0                np19py27_0
pcre                      8.31                          0
pep8                      1.6.2                    py27_0
petsc                     3.4.5                    py27_1
petsc4py                  3.4                      py27_1
pillow                    2.7.0                    py27_1
pip                       6.1.1                    py27_0
pixman                    0.26.2                        0
ply                       3.4                      py27_0
psutil                    2.2.1                    py27_0
ptyprocess                0.4                      py27_0
py                        1.4.26                   py27_0
py2cairo                  1.10.0                   py27_2
pyasn1                    0.1.7                    py27_0
pycosat                   0.6.1                    py27_0
pycparser                 2.10                     py27_0
pycrypto                  2.6.1                    py27_0
pycurl                    7.19.5.1                 py27_0
pyflakes                  0.8.1                    py27_0
pygments                  2.0.2                    py27_0
pyopenssl                 0.14                     py27_0
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.3                   py27_0
pytables                  3.1.1                np19py27_2
pytest                    2.6.4                    py27_0
python                    2.7.9                         2
python-dateutil           2.4.1                    py27_0
pytz                      2015.2                   py27_0
pyyaml                    3.11                     py27_0
pyzmq                     14.5.0                   py27_0
qt                        4.8.6                         1
readline                  6.2                           2
redis                     2.6.9                         0
redis-py                  2.10.3                   py27_0
requests                  2.6.0                    py27_0
rope                      0.9.4                    py27_1
runipy                    0.1.3                    py27_0
scientificpython          2.9.4                    py27_9
scikit-image              0.11.2               np19py27_0
scikit-learn              0.15.0b1            np18py27_p0  [mkl]
scipy                     0.14.0              np18py27_p0  [mkl]
setuptools                15.0                     py27_0
sip                       4.16.5                   py27_0
six                       1.9.0                    py27_0
slepc                     3.4.4                    py27_2
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.2.3                    py27_0
spyder                    2.3.4                    py27_1
spyder-app                2.3.4                    py27_0
sqlalchemy                0.9.9                    py27_0
sqlite                    3.8.4.1                       1
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1                np19py27_0
swig                      3.0.2                         0
sympy                     0.7.6                    py27_0
system                    5.8                           2
tables                    3.1.1                     <pip>
terminado                 0.5                      py27_0
theano                    0.6.0                np19py27_0
tk                        8.5.18                        0
toolz                     0.7.1                    py27_0
tornado                   4.1                      py27_0
ufl                       1.4.0                    py27_1
ujson                     1.33                     py27_0
unicodecsv                0.9.4                    py27_0
util-linux                2.21                          0
vtk                       5.10.1                   py27_1
werkzeug                  0.10.1                   py27_0
xlrd                      0.9.3                    py27_0
xlsxwriter                0.6.7                    py27_0
xlwt                      0.7.5                    py27_0
yaml                      0.1.4                         0
zeromq                    4.0.4                         0
zlib                      1.2.8                         0
[xqian29@aci-service-1 python]$

**Comment by astrojuanlu** [comment]
Hello @xpqian, I think I solve the issue with slepc. Could you please do the following steps?

```
$ source activate fenics27
(fenics27) $ conda install "slepc==3.4.4" --channel https://conda.binstar.org/juanlu001/channel/fenics:1.4.0:centos"
(fenics27) $ conda list slepc
slepc    3.4.4     py27_3
```

The last line is the important one: build 3 is the updated build I just uploaded which should fix the problem.

**Comment by astrojuanlu** [comment]
Closing this issue, feel free to reopen if it persists.
