### ISSUE TITLE
local building error

### ISSUE THREAD

**Issue by xpqian** [Juanlu001/fenics-recipes#11]
When I tried local building with "conda build boost eigen3 petsc petsc4py instant ufl fiat ffc dolfin fenics --python 27" on Scientific Linux release 6.3 (Carbon), it gave me the following error:

"Error: no such directory: /home/xqian29/boost"

Any help is greatly appreciated.

**Comment by astrojuanlu** [comment]
Hello @xpqian, you are probably in the wrong directory or first have to download the repository. I shall add these instructions to the `README`.

Please download https://github.com/Juanlu001/fenics-recipes/archive/maint-1.4.0.zip and then unzip it in your desired location.
