### ISSUE TITLE
mshr

### ISSUE THREAD

**Issue by twmr** [Juanlu001/fenics-recipes#12]
please add the meshing tool `mshr` to your fenics recipes

**Comment by astrojuanlu** [comment]
Thanks for the suggestion @thisch and sorry for the delay!

If I understood correctly from here:

https://bitbucket.org/benjamik/mshr

The installation procedure is just `cmake . && make && make install` and the requirements are DOLFIN,  Gnu GMP and Gnu MPFR. Is that right?

**Comment by twmr** [comment]
No, don't use https://bitbucket.org/benjamik/mshr. Use the repo from https://bitbucket.org/fenics-project/mshr instead. The default cmake installation procedure (`cmake . && make && make install`) should work. It should compile with the dependencies mentioned by you.

**Comment by twmr** [comment]
Any updates on this?

**Comment by astrojuanlu** [comment]
No updates, I was focused on solving some pending issues with DOLFIN. I will work on this next, thanks for the remainder.

**Comment by twmr** [comment]
Great to hear this. Thx!

**Comment by RafalSkolasinski** [comment]
There are people in our group who would also be happy for having mshr with conda : - )

**Comment by basnijholt** [comment]
I've been waiting for this too :+1:

**Comment by astrojuanlu** [comment]
By popular acclaim, I am working on it right now :)

**Comment by RafalSkolasinski** [comment]
It's great to hear that :)

**Comment by astrojuanlu** [comment]
I just added a mshr recipe, but haven't uploaded the package yet because I am not sure how to run the tests. @thisch could you give me a pointer? Here is the source: https://github.com/Juanlu001/fenics-recipes/tree/4b99e6460cff4fead00c7466ef79d4fdf34d5b0a/mshr

**Comment by twmr** [comment]
If you want to run the tests (at compile time) you have to set the `ENABLE_TESTS` cmake option with `-DENABLE_TESTS=1` before compiling mshr. Then you can run `make test` in the build directory. 

HTH

**Comment by astrojuanlu** [comment]
Just added the complete recipe and uploaded the package. People watching this issue, please test it and open an issue if something goes wrong :)

**Comment by basnijholt** [comment]
Great! Thanks a lot.
