### ISSUE TITLE
Trouble with fenics Binary installation using conda on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by DavidSanwald** [Juanlu001/fenics-recipes#13]
Hello,

I'm trying to user fenics with the anaconda distribution on Ubuntu but somehow I can't get it to work properly.

After

```
conda config --add channels juanlu001
source activate fenics27
conda install fenics  # This will work now
```

I get 

```
Fetching packages ...
Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/juanlu001/linux-   64/eigen3-3.2.1-0.tar.bz2
```

Trying what was suggested in another thread with a similar problem:

```
(fenics27) $ conda install eigen3 --channel https://conda.binstar.org/juanlu001/channel     /fenics:1.4.0:centos
```

gave me

```
Fetching packages ...
Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/juanlu001/linux-64/eigen3-3.2.1-0.tar.bz2
```

I'm not a very experienced user, so maybe I'm doing something wrong. Is there any way to solve this problem? I'd be very relieved if I could get help.

Sincerely ,
David

**Comment by astrojuanlu** [comment]
Hello @I-like-foxes, thanks for the bug report and sorry for the delay. This problem is the same as #17, so I will close this issue as duplicate. You can follow the discussion there, I will try to fix this within today.
