### ISSUE TITLE
Missing eigen3 package

### ISSUE THREAD

**Issue by rwillmers** [Juanlu001/fenics-recipes#17]
Hello, I'm not sure this is the correct place to report problems with conda installation of FEniCS, but there you go.
I think there may be a problem with file names of the eigen3 package. My installation fails with
(fenics27)ramiro@suse:~/anaconda> conda install -c https://conda.binstar.org/juanlu001 eigen3
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /home/ramiro/anaconda/envs/fenics27:

The following packages will be downloaded:

| package | build |
| --- | --- |
| eigen3-3.2.1 | 0         524 KB |

The following NEW packages will be INSTALLED:

```
eigen3: 3.2.1-0
```

Proceed ([y]/n)? y

Fetching packages ...
Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/juanlu001/linux-64/eigen3-3.2.1-0.tar.bz2

(fenics27)ramiro@suse:~/anaconda> 

Going with the browser directly to this directory, I fetched a file named 

linux-64_eigen3-3.2.1-0.tar.bz2

I don't know if the system is supposed to do some automatic prefixing of the architecture to the 
file name, so this may be correct, but somehow is not working for me.

Many thanks for your time!

Ramiro.

**Comment by astrojuanlu** [comment]
Hello @rwillmers, thanks for the bug report and sorry for the delay. This is actually my fault because I had some problems with this specific package, I am going to fix this today once and for all.

**Comment by astrojuanlu** [comment]
Pinging @rwillmers @I-like-foxes and @porphyrius: I already cleaned everything upstream and eigen3 should be installable using the main channel. Can you check that this at least works? (That is: no 404 error in the last step)

```
conda install eigen3 -c juanlu001
```

Now I am going to update the dependency links of the rest of the packages just to make sure that nobody will encounter this problem ever.

**Comment by rwillmers** [comment]
Jesus, you're fast ;)
You didn't even give me time to reply to the first message.
I was going to say that you didn't have to apologize for being late, it's
not like this it's your job or like you owe me anything.
The packaging you did will save me so much trouble in the future I don't
even know how to begin to thank you. ( I'm talking about fenics )
I'll check this out first thing tomorrow.
Many thanks again,
Ramiro.

Pinging @rwillmers https://github.com/rwillmers @I-like-foxes
https://github.com/I-like-foxes and @porphyrius
https://github.com/porphyrius: I already cleaned everything upstream and
eigen3 should be installable using the main channel. Can you check that
this at least works? (That is: no 404 error in the last step)

conda install eigen3 -c juanlu001

Now I am going to update the dependency links of the rest of the packages
just to make sure that nobody will encounter this problem ever.

**Comment by astrojuanlu** [comment]
Your kind words are highly appreciated :) Hope you are right and it
effectively ends up being useful!

**Comment by rwillmers** [comment]
We're almost there. I think there is still a problem with a module that is not been properly recompiled and depends on an older build:

ramiro@suse:~> ls ~/anaconda/envs
ramiro@suse:~> conda create --name fenics27 python=2.7
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/ramiro/anaconda/envs/fenics27:

The following NEW packages will be INSTALLED:

```
openssl:    1.0.1k-1    
pip:        6.1.1-py27_0
python:     2.7.9-3     
readline:   6.2-2       
setuptools: 15.2-py27_0 
sqlite:     3.8.4.1-1   
system:     5.8-2       
tk:         8.5.18-0    
zlib:       1.2.8-0     
```

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##############################################################################| 100%
#
# To activate this environment, use:
# $ source activate fenics27
#
# To deactivate this environment, use:
# $ source deactivate
#
ramiro@suse:~> source activate fenics27
discarding /home/ramiro/anaconda/bin from PATH
prepending /home/ramiro/anaconda/envs/fenics27/bin to PATH

(fenics27)ramiro@suse:~> conda install fenics --channel juanlu001
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /home/ramiro/anaconda/envs/fenics27:

The following NEW packages will be INSTALLED:

```
boost:        1.57.0-0         
cmake:        3.0.1-0          
dolfin:       1.5.0-np19py27_1 
eigen3:       3.2.1-1          
fastcache:    1.0.2-py27_0     
fenics:       1.5.0-0          
ffc:          1.5.0-np19py27_1 
fiat:         1.5.0-np19py27_1 
fontconfig:   2.11.1-3         
freetype:     2.5.2-1          
instant:      1.5.0-np19py27_1 
libpng:       1.5.13-1         
libxml2:      2.9.0-0          
mkl:          11.1-np19py27_p3 
mkl-rt:       11.1-p0          
mkl-service:  1.0.0-py27_p1    
mpi4py:       1.3-py27_0       
mpich2:       1.4.1p1-0        
nose:         1.3.6-py27_0     
numexpr:      2.3.1-np19py27_0 
numpy:        1.9.2-py27_0     
pcre:         8.31-0           
petsc:        3.5.2-py27_1     
petsc4py:     3.5.1-py27_1     
ply:          3.6-py27_0       
qt:           4.8.6-2          
scikit-learn: 0.15.2-np19py27_0
scipy:        0.15.1-np19py27_0
six:          1.9.0-py27_0     
swig:         3.0.2-0          
sympy:        0.7.6-py27_0     
ufl:          1.5.0-py27_1     
vtk:          5.10.1-py27_1    
```

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##############################################################################| 100%
(fenics27)ramiro@suse:~> python -c "from dolfin import _"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ramiro/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/**init**.py", line 16, in <module>
    from . import cpp
  File "/home/ramiro/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/**init**.py", line 42, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/home/ramiro/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 32, in <module>
    _common = swig_import_helper()
  File "/home/ramiro/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
ImportError: libboost_filesystem.so.1.55.0: cannot open shared object file: No such file or directory
(fenics27)ramiro@suse:~> (fenics27)ramiro@suse:~> ls ~/anaconda/envs/fenics27/lib/libboost_files_
/home/ramiro/anaconda/envs/fenics27/lib/libboost_filesystem.a
/home/ramiro/anaconda/envs/fenics27/lib/libboost_filesystem.so
/home/ramiro/anaconda/envs/fenics27/lib/libboost_filesystem.so.1.57.0

It's trying to load .1.55.0, but anaconda installed 1.57.0.

Ops, it's going to have problems with other libraries as well:

(fenics27)ramiro@suse:~/anaconda/envs/fenics27> cd ./lib/python2.7/site-packages/dolfin/cpp/
(fenics27)ramiro@suse:~/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp> ldd _common.so | grep -i "not found"
./_common.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./_common.so)
./_common.so: /usr/lib64/libgomp.so.1: version`GOMP_4.0' not found (required by /home/ramiro/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/./../../../../libdolfin.so.1.5)
./_common.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/ramiro/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/./../../../../libdolfin.so.1.5)
./_common.so: /usr/lib64/libstdc++.so.6: version`GLIBCXX_3.4.20' not found (required by /home/ramiro/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/./../../../../libdolfin.so.1.5)
        libboost_filesystem.so.1.55.0 => not found
        libboost_program_options.so.1.55.0 => not found
        libboost_system.so.1.55.0 => not found
        libboost_thread.so.1.55.0 => not found
        libboost_iostreams.so.1.55.0 => not found
        libcppunit-1.13.so.0 => not found
        libboost_filesystem.so.1.55.0 => not found
        libboost_program_options.so.1.55.0 => not found
        libboost_system.so.1.55.0 => not found
        libboost_thread.so.1.55.0 => not found
        libboost_iostreams.so.1.55.0 => not found
        libcppunit-1.13.so.0 => not found

The first ones, related to g++ libraries, are possibly my doing something wrong, I'll reinstall anaconda later to verify, but I think the latter ones should have come with the fenics installation.

Many thanks again for your time!

**Comment by rwillmers** [comment]
Sorry! Pressed the wrong button! New at this!

**Comment by rwillmers** [comment]
Sorry again :)
I didn't mean to close this issue! Please someone take me away from the keyboard before I break something!

**Comment by astrojuanlu** [comment]
The boost requirement is my fault too, I will have to fix it. Regarding the g++ libraries... which is your operative system? Perhaps this is the same as #8 (see for instance https://github.com/Juanlu001/fenics-recipes/issues/8#issuecomment-91230825).

**Comment by astrojuanlu** [comment]
For reference: the boost issue is #6

**Comment by astrojuanlu** [comment]
We can go on with the conversation but the original issue can be actually closed :)

**Comment by rwillmers** [comment]
I'm sorry again :)
I thought it wasn't mine to close.

Hopefuly using e-mail I don't close or open anything inadvertently.

Many thanks again,

Ramiro.

On 14-05-2015 09:13, Juan Luis Cano Rodríguez wrote:

> We can go on with the conversation but the original issue can be
> actually closed :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Juanlu001/fenics-recipes/issues/17#issuecomment-102017140.

## 

Ramiro Brito Willmersdorf  tel: +55-81-2126-8231r245 cel: +55-81-9966-2941
DEMEC/UFPE   hangouts:ramiro@willmersdorf.net   skype: ramiro.willmersdorf
