### ISSUE TITLE
boost mismatch: fenics-recipes requires 1.55, conda provides 1.57

### ISSUE THREAD

**Issue by mzaffalon** [Juanlu001/fenics-recipes#19]
`conda install fenics --channel juanlu001` installs boost 1.57.0-1 from Anaconda but `import dolfin` complains about missing `libboost_filesystem.so.1.55.0`:

```
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import dolfin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michele/local/miniconda/lib/python2.7/site-packages/dolfin/__init__.py", line 16, in <module>
    from . import cpp
  File "/home/michele/local/miniconda/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 42, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/home/michele/local/miniconda/lib/python2.7/site-packages/dolfin/cpp/common.py", line 32, in <module>
    _common = swig_import_helper()
  File "/home/michele/local/miniconda/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
ImportError: libboost_filesystem.so.1.55.0: cannot open shared object file: No such file or directory
```

I am on Debian testing, 64 bits. I am not sure if this is related to #6.

**Comment by mzaffalon** [comment]
I see it is: ContinuumIO/anaconda-issues#247.

**Comment by mzaffalon** [comment]
And `conda search boost` returns only version 1.57.0, so it is not even possible to force conda to install boost 1.55.

**Comment by astrojuanlu** [comment]
You are right @michele-zaffalon, I don't know how much time do the Anaconda guys need to solve it, but still the wrong specification is a problem on my side already reported in #6. Closing this as duplicate.

**Comment by astrojuanlu** [comment]
Well, Anaconda boost already has all the required libraries! :smile: Now there should be no further problems, but I will keep an eye on it just in case.

**Comment by mzaffalon** [comment]
Not sure if you uploaded the new version, but if I follow the instructions here http://fenicsproject.org/download/#installation-from-conda-packages, I get the same error message, missing boost 1.55 library.

**Comment by astrojuanlu** [comment]
`conda search boost` won't give 1.55, for that you also have to use my channel: `conda search boost -c juanlu001`

**Comment by astrojuanlu** [comment]
And nope, I didn't upload the new versions yet - I am in low connectivity until next week unfortunately :/

**Comment by mzaffalon** [comment]
No problem. libblas seems to be missing.

**Comment by astrojuanlu** [comment]
Is libblas missing? In theory it should be provided by mkl, did you install
it?

**Comment by mzaffalon** [comment]
That was missing.
