### ISSUE TITLE
Dependency not met

### ISSUE THREAD

**Issue by roliveira** [Juanlu001/fenics-recipes#2]
I'm using the steps provided at FEniCS [website](http://fenicsproject.org/download/) to install it with conda package manager:

``` bash
$ conda create -n fenics27 python=2.7 ipython=2.2
$ source activate fenics27
(fenics27) $ conda install fenics --channel juanlu001
```

By doing so, I get the following error message when trying `import fenics`:

```
 ---------------------------------------------------
 DOLFIN runtime dependency is not met.
 Install the following python module: 'ffc'
 and make sure its location is listed in PYTHONPATH.
 ---------------------------------------------------
```

Additionally if I try to `import ffc` I get this message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/ffc/__init__.py", line 21, in <module>
    from ffc.jitcompiler import jit
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/ffc/jitcompiler.py", line 30, in <module>
    import ufc
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/__init__.py", line 7, in <module>
    from .ufc import (cell,
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/ufc.py", line 32, in <module>
    _ufc = swig_import_helper()
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/ufc.py", line 28, in swig_import_helper
    _mod = imp.load_module('_ufc', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/ufc/_ufc.so)
```

The `ffc` library is installed and listed under the `~/anaconda/envs/fenics27/bin` which is in the environment path. 

Have I missed a step?

**Comment by astrojuanlu** [comment]
Hello @oliveirarodolfo! What Linux distro are you using? Perhaps it is too old, try following this advice:

http://fenicsproject.org/download/installation_using_conda.html#importerror-lib64-libc-so-6-version-glibc-2-14-not-found

**Comment by roliveira** [comment]
Hi @Juanlu001,

I'm running CentOS 6.3 (no root access) and I've tried what you suggested. It worked but with one pitfall, I could not find the `boost-1.55.0-1` package when installing from the `fenics:1.4.0:centos` channel:

```
Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/juanlu001/channel/fenics:1.4.0:centos/linux-64/boost-1.55.0-1.tar.bz2
```

I solved this by adding the `juanlu001` as well as the `fenics:1.4.0:centos` channel.

``` bash
$ conda config --add channels juanlu001
$ conda config --add channels https://conda.binstar.org/juanlu001/channel/fenics:1.4.0:centos
```

And now I can install it using the `fenics=1.4.0` version.

``` bash
$ conda install "fenics=1.4.0"
```

However now I found an error with `libbz2.so.1.0`:

``` python
>>> import fenics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/fenics/__init__.py", line 6, in <module>
    from dolfin import *
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/__init__.py", line 16, in <module>
    import cpp
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 42, in <module>
    exec("import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 32, in <module>
    _common = swig_import_helper()
  File "/home/USER/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

I tried the steps mentioned on the [Re: [FEniCS-support] Conda package for FEniCS](https://www.mail-archive.com/fenics-support@fenicsproject.org/msg01141.html) message but had no luck yet...

I don't think that I thanked you for the work, great job!

**Comment by astrojuanlu** [comment]
Thanks for the compliments! :) We are making progress. Thanks for telling me about boost, I screwed something up lately and will fix it ASAP.

It is strange that libbz2 is not found though, can you post the output of `whereis libbz2`? There is no conda package for it so let's see if it is just a version mismatch.

**Comment by roliveira** [comment]
Well it turned out that `whereis libbz2` wasn't returning anything soon after I got it, another lib problem came out and so on. I would probably have to put this aside for now as I do not have much time to work on it right now... 

Anyhow thanks for the help @Juanlu001!

**Comment by astrojuanlu** [comment]
So you mean that you installed `libbz2` and then more lib problems came? Anyway I will leave this open so when you have some more spare time we can fix the issue. Thanks to you!

**Comment by astrojuanlu** [comment]
I think I already fixed the broken channel thing. Closing this!

**Comment by roliveira** [comment]
I'm still on the same page... As soon as I can I'll try it again and will let you know!
