### ISSUE TITLE
DOLFIN runtime dependency is not met. Install the following python module: 'ffc' and make sure its location is listed in PYTHONPATH.

### ISSUE THREAD

**Issue by jonmilby** [Juanlu001/fenics-recipes#21]
After installing Anaconda and fenics on CentOS 6.6 or 7, I am having an issue.  
Running "from dolfin import *"

Fails with the error:
$ python template_timedep.py
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days

DOLFIN runtime dependency is not met.
Install the following python module: 'ffc'
and make sure its location is listed in PYTHONPATH.

**Comment by astrojuanlu** [comment]
Hello @jonmilby, could you please try `python -c "import ffc"`? This error is very common and has nothing to do with a missing ffc.

**Comment by astrojuanlu** [comment]
Feedback needed, please reopen if error persists.

**Comment by jbcolli2** [comment]
Hello,
   I am also having this problem as well.  I am running Spyder on a Mac with Yosemite.  I get the exact same error message.  I tried running python -c "import ffc" and it has not fixed the problem.  Can you please explain what the problem is?

**Comment by astrojuanlu** [comment]
Hello @jbcolli2, what is the error message that you see when you try `python -c "import fcc"`?

**Comment by jbcolli2** [comment]
Hello @Juanlu001 ,
   There actually wasn't an error message.  Executed the command in the terminal with Spyder closed.  I opened Spyder and tried to run a Fenics program and got the same message as above.

**Comment by astrojuanlu** [comment]
I didn't quite understand, would you please try typing in a Python or IPython terminal

``` python
>>> import fcc
```

and paste the output?

**Comment by jbcolli2** [comment]
I have two python terminals I can use.  The one I get through the Mac
terminal will import ffc fine.  This is because the mac terminal is set up
to run Fenics.  When I type in "import ffc" to the python terminal in
Spyder I get the following message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'fcc'

Do you think the problem is with Spyder not being set up correctly to find
ffc?  I've put the ffc path into the PYTHONPATH variable in Spyder.

On Fri, Sep 4, 2015 at 10:42 AM, Juan Luis Cano Rodríguez <
notifications@github.com> wrote:

> I didn't quite understand, would you please try typing in a Python or
> IPython terminal
> 
> > > > import fcc
> 
> and paste the output?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Juanlu001/fenics-recipes/issues/21#issuecomment-137771962
> .

## 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by astrojuanlu** [comment]
On 2015-09-04 18:02, Jeb Collins wrote:

> When I type in "import ffc" to the python terminal in
> Spyder I get the following message:
> 
> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> ImportError: No module named 'fcc'
> 
> Do you think the problem is with Spyder not being set up correctly to find
> ffc? I've put the ffc path into the PYTHONPATH variable in Spyder.

Yes, it definitely looks like a misconfiguration in Spyder then. I am 
sorry but I cannot help with that :/ You can try printing `sys.path` to 
see if something is wrong or asking in sites like superuser.com.

**Comment by jbcolli2** [comment]
Ok, thanks for your help.

On Friday, September 4, 2015, Juan Luis Cano Rodríguez <
notifications@github.com> wrote:

> On 2015-09-04 18:02, Jeb Collins wrote:
> 
> > When I type in "import ffc" to the python terminal in
> > Spyder I get the following message:
> > 
> > Traceback (most recent call last):
> > File "<stdin>", line 1, in <module>
> > ImportError: No module named 'fcc'
> > 
> > Do you think the problem is with Spyder not being set up correctly to
> > find
> > ffc? I've put the ffc path into the PYTHONPATH variable in Spyder.
> 
> Yes, it definitely looks like a misconfiguration in Spyder then. I am
> sorry but I cannot help with that :/ You can try printing `sys.path` to
> see if something is wrong or asking in sites like superuser.com.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Juanlu001/fenics-recipes/issues/21#issuecomment-137780684
> .

## 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by kilojoules** [comment]
I got this problem too from brew dolfin. Here's the error I got:

```
$ python -c "import ffc"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ffc/__init__.py", line 18, in <module>
    from ffc.compiler import compile_form, compile_element
  File "/usr/local/lib/python2.7/site-packages/ffc/compiler.py", line 121, in <module>
    from ffc.log import info, info_green, warning
  File "/usr/local/lib/python2.7/site-packages/ffc/log.py", line 31, in <module>
    from ufl.common import dstr, tstr
ImportError: No module named common
```

**Comment by divyabohra** [comment]
I get the same errors but only after I install matplotlib in the same anaconda environment as fenics. Without matplotlib, I get no error and everything works fine. Can someone help?
