### ISSUE TITLE
Fix clang compilation on OS X

### ISSUE THREAD

**Issue by astrojuanlu** [Juanlu001/fenics-recipes#3]
I don't have access to a OS X machine but it should be easy to build the FEniCS packages there one and provide binaries. Anyone care to help?

**Comment by roliveira** [comment]
Hey, it's me again!

Here is my list so far:
- [x] `fiat`
- [x] `ufl`
- [x] `instant`
- [x] `eigen3`
- [x] `boost`. 
- [x] `petsc` --> https://binstar.org/guyer/petsc
- [x] `petsc4py` --> https://binstar.org/guyer/petsc4py
- [ ] `ffc`  --> I'm stuck here!
- [ ] `dolfin`
- [ ] `fenics`

**Comment by astrojuanlu** [comment]
Hello @oliveirarodolfo! Are you trying to compile these in OS X? Which specific problems are you having with FFC?

**Comment by roliveira** [comment]
Hey @Juanlu001,

I am trying the OS X but right now this is what I get:

``` bash
*************** SUMMARY ***************

  Number of tests:                  464

  Num ffc fail:                       0
  Num gcc fail:                       0
  Num run fail:                       0
  Num correct:        (tol. 1e-14): 202
  Num diff. critical: (tol. 1e-08):   0
  Num diff. acceptable:             262
  Total:                            464

.................In instant.recompile: The module did not compile with command 'make VERBOSE=1', see '/Users/USER/.instant/error/ffc_form_93b539692c2d8961bd5535661fe4f1ae078b0307/compile.log'
E..........................
======================================================================
ERROR: testPoisson (misc.test.JITTests)
Test that JIT compiler is fast enough.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/USER/Python/anaconda/conda-bld/work/ffc-1.5.0/test/unit/misc/test.py", line 335, in testPoisson
    jit(a0, options)
  File "/Users/USER/Python/anaconda/envs/_test/lib/python2.7/site-packages/ffc/jitcompiler.py", line 74, in jit
    return jit_form(ufl_object, parameters)
  File "/Users/USER/Python/anaconda/envs/_test/lib/python2.7/site-packages/ffc/jitcompiler.py", line 148, in jit_form
    cache_dir = cache_dir)
  File "/Users/USER/Python/anaconda/envs/_test/lib/python2.7/site-packages/ffc/backends/ufc/build.py", line 73, in build_ufc_module
    **kwargs)
  File "/Users/USER/Python/anaconda/envs/_test/lib/python2.7/site-packages/instant/build.py", line 563, in build_module
    recompile(modulename, module_path, new_compilation_checksum, build_system)
  File "/Users/USER/Python/anaconda/envs/_test/lib/python2.7/site-packages/instant/build.py", line 165, in recompile
    instant_error(msg % (cmd, compile_log_filename_dest))
  File "/Users/USER/Python/anaconda/envs/_test/lib/python2.7/site-packages/instant/output.py", line 85, in instant_error
    raise RuntimeError(text)
RuntimeError: In instant.recompile: The module did not compile with command 'make VERBOSE=1', see '/Users/USER/.instant/error/ffc_form_93b539692c2d8961bd5535661fe4f1ae078b0307/compile.log'

----------------------------------------------------------------------
Ran 44 tests in 296.210s

FAILED (errors=1)
```

I'm not that sure where can I set the `make VERBOSE=1` flag. Any clue?

**Comment by astrojuanlu** [comment]
In this cases what you should do is look for the error log, in this case `/Users/USER/.instant/error/ffc_form_93b539692c2d8961bd5535661fe4f1ae078b0307/compile.log`, and see its contents. Please upload it to gist.github.com so we can diagnose what it is happening here! I suspect this will have to be reported to the main devs though.

**Comment by oseledets** [comment]
I have the same problem. The gist is here. https://gist.github.com/28d6895d38d39bff5a31
Apparently, it is this problem: http://stackoverflow.com/questions/13445742/apple-and-shared-ptr which probably can be fixed by passing correct flags to the clang compiler.

**Comment by astrojuanlu** [comment]
Thanks for the heads up @oseledets, probably the compilation in OS X requires some specific tuning. The core devs already provide OS X 10.9 and 10.10 binaries so there must be a way - I don't have a Mac myself so if any of you care to ask for help in the mailing list we can make it :smile:

**Comment by astrojuanlu** [comment]
This is actually a duplicate of #16.
