### ISSUE TITLE
Update recipes for better portability

### ISSUE THREAD

**Issue by astrojuanlu** [Juanlu001/fenics-recipes#37]
@stuarteberg Made some recommendations here: https://github.com/ContinuumIO/anaconda-issues/issues/483#issuecomment-149262721

I have a problem with the first rule though:

> In `meta.yaml`, always include `gcc` as a build dependency, never a run dependency.

The fact is that `instant` is a just-in-time compiler, so I actually need `gcc` as a run dependency. Should I add `libgcc` too then?

**Comment by stuarteberg** [comment]
I didn't realize that your package was a JIT.  Perhaps the rules I listed were worded too strongly.

> Should I add libgcc too then?

No, the `gcc` package is a superset of the `libgcc` package.  If you have it as a run dependency, there's no benefit to also including `libgcc`.

**Comment by astrojuanlu** [comment]
> No, the `gcc` package is a superset of the `libgcc` package.  If you have it as a run dependency, there's no benefit to also including `libgcc`.

Got it, thanks. Let's see if I can provide at least an almost-portable version of the packages.

**Comment by astrojuanlu** [comment]
I found something stunning: using

``` bash
CC=${PREFIX}/bin/gcc
CXX=${PREFIX}/bin/g++
```

leads to CHOLMOD related errors, whereas

``` bash
CC=${PREFIX}/bin/cc
CXX=${PREFIX}/bin/c++
```

have no side effects. `cc` is identical to `gcc` and `c++` is identical to `g++`. I will need another day to find the will to debug this, but so far it works.

**Comment by astrojuanlu** [comment]
I'm closing this issue because I managed to compile the packages but I'll have to bring back VTK support at some point. Thanks for your help!
