### ISSUE TITLE
Atlas/Lapack instead of MKL trial version?

### ISSUE THREAD

**Issue by dajuno** [Juanlu001/fenics-recipes#38]
Hello,

I just installed fenics with conda through your repository. I see you included the commercial MKL library 
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days <--- !!

while the fenics source installer uses ATLAS+LAPACK, and so do (of course) the versions included in the Linux distributions. conda numpy uses openblas.

Why have you chosen not to use the free packages over the MKL demo? Can I build fenics without it, using conda and your recipes?

Thanks!

**Comment by astrojuanlu** [comment]
Hello @dajuno, you raise a very valid concern. The easiest thing for me was to use Intel MKL libraries at first, and that's why I chose it over other alternatives. I accept advice, guidance or even pull requests to make FEniCS + OpenBLAS a reality :)

**Comment by astrojuanlu** [comment]
Here's the other reason: OpenBLAS has been available in Anaconda for just one month.

https://anaconda.org/anaconda/openblas/files

**Comment by astrojuanlu** [comment]
I am about to make it but I need to build petsc4py against NumPy 1.9 and there's an issue blocking me: https://github.com/conda/conda-build/issues/648

**Comment by dajuno** [comment]
Great, thanks! :)

**Comment by astrojuanlu** [comment]
By the way, I just saw this: https://twitter.com/bryvdv/status/660672659752022016 "the MKL optimizations for NumPy available free to all"
