### ISSUE TITLE
Error while building fenics using maint-1.4.0 branch of the recipes

### ISSUE THREAD

**Issue by ghost** [Juanlu001/fenics-recipes#4]
Hi,

I have problems installing fenics via conda in a (old) cluster running RHEL 5. Initial problems of trying to install fenics1.5 (error message: ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found), lead me to believe it's better to install 1.4 version. After communicating with juanlu001 about the similar error after installing fenics1.4 (ImportError: /usr/lib64/libstdc++.so.6: version`GLIBCXX_3.4.11' not found), we concluded that the system in the cluster that I am using is just old, and I need to build locally.

I follow his suggestion to compile from fenics1.4 recipe using conda build:
$conda build boost eigen3 petsc petsc4py instant ufl fiat ffc dolfin fenics --python 27

then I got the following error when compiling petc4py:
Cloning into bare repository '/home/ahakim/miniconda/conda-bld/git_cache/__bitbucket.org_petsc_petsc4py_'...
error: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed while accessing https://bitbucket.org/petsc/petsc4py/info/refs?service=git-upload-pack
fatal: HTTP request failed

Here is my conda info:
Current conda install:

```
         platform : linux-64
    conda version : 3.10.0
```

  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.5.3
     root environment : /home/ahakim/miniconda  (writable)
  default environment : /home/ahakim/miniconda/envs/otf
     envs directories : /home/ahakim/miniconda/envs
        package cache : /home/ahakim/miniconda/pkgs
         channel URLs : https://conda.binstar.org/juanlu001/channel/fenics:1.4.0:centos/linux-64/
                        https://conda.binstar.org/juanlu001/channel/fenics:1.4.0:centos/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/ahakim/.condarc
    is foreign system : False

Can anyone please advice me on this problem? Thanks

-Ara

**Comment by astrojuanlu** [comment]
Hi @aradearh,

Well, this has nothing to do with the packages (yet), but apparently there was some problem with the download. I googled and found that these are due to an old git version:

https://help.github.com/articles/https-cloning-errors/

If you are not able to update your git version (which I suspect is the case) you will have to edit the recipe to make it download a zip instead of cloning a repository. You will have to specify this:

```
source:
  fn: maint-3.4.zip
  url: https://bitbucket.org/petsc/petsc4py/get/maint-3.4.zip
```

I got the link from here:

https://bitbucket.org/petsc/petsc4py/downloads

In general, you have to do this for all the recipes depending on a git repository.

**Comment by astrojuanlu** [comment]
Hello @aradearh, I changed the recipe according to your feedback so git is no longer needed. This way we avoid problems with old git versions. I will update the packages this weekend so I consider this can be closed.
