### ISSUE TITLE
Mac OS X Installation

### ISSUE THREAD

**Issue by earendilllock** [Juanlu001/fenics-recipes#41]
Hi, dear all!

Is it possible to obtain fenics on OS X via anaconda?

when I've tried to do so the following error was obtained (and there is no conda package for dolfin on OS X)

```
Error: Could not find some dependencies for fenics: dolfin ==1.5.0
```

**Comment by astrojuanlu** [comment]
Hi @earendilllock, unfortunately there are some issues preventing FEniCS to be compiled on OS X, namely these ones: https://github.com/Juanlu001/fenics-recipes/labels/osx If you would like to help with testing that would be appreciated! I'm leaving this one as a meta-issue.

**Comment by earendilllock** [comment]
I'm trying to build dolfin from https://bitbucket.org/fenics-project/dolfin.git and (if it would be succesfull) the conda package i hope would be possible to create.

(And I will be very pleased to help, but I do not know how =) cause I'm not a pro)

**Comment by astrojuanlu** [comment]
No need of having a meta-issue actually, I'm closing this.
