### ISSUE TITLE
How can I use IDE, say Spyder, after conda binary installation?

### ISSUE THREAD

**Issue by wang1943** [Juanlu001/fenics-recipes#49]
Hi, Juan,

Thanks for the great work to make fenics easier with the binary source. However I'm wondering how to make an IDE(say spyder) works after activate fenics environment. I have little knowledge of how conda actually work. It appears that if fenics is not activated, I can't import fenics in anaconda environment. Should I just install spyder while env fenics is activated using
:/conda install spyder
or there are other tricks I can do?

Thanks.

**Comment by astrojuanlu** [comment]
Hi @wang1943, fortunately you can activate the same environment where you installed FEniCS and install spyder there:

``` bash
$ source activate fenics27
(fenics27) $ conda install spyder
(fenics27) $ spyder
```
