### ISSUE TITLE
ImportError when trying to import dolfin

### ISSUE THREAD

**Issue by bcrestel** [Juanlu001/fenics-recipes#5]
The installation went well. But when I open python from the fenics27 environment and type `from dolfin import *`, I get the following error msg:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/fenics/__init__.py", line 6, in <module>
    from dolfin import *
  File "/workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/__init__.py", line 4, in <module>
    import dolfin.importhandler
  File "/workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/importhandler/__init__.py", line 13, in <module>
    import numpy
  File "/workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/numpy/__init__.py", line 172, in <module>
    from . import add_newdocs
  File "/workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: /workspace/ben/anaconda/envs/fenics27/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: Py_InitModule4_64
[50130 refs]
```

Any idea?

**Comment by astrojuanlu** [comment]
This is very weird, I have never seen an error like that and Google suggests some relationship with debug flags in Python. Can you post the output of these commands?

```
source activate fenics27
python -c "import sysconfig; print(sysconfig.get_config_vars())"
conda info -a
```

**Comment by bcrestel** [comment]
I posted both outputs in the following github repo:
https://github.com/bcrestel/DebugFiles4FenicsOnConda

**Comment by astrojuanlu** [comment]
It seems that you have the debug Python version installed somehow. Would you post the output of

```
source activate fenics27
conda list
```

to confirm?

In principle, removing the `debug` package should be enough to bring back the normal Python:

```
conda remove debug
```

**Comment by bcrestel** [comment]
You are correct; I have the debug version. I installed python 2.7.7 instead.
$ conda list
boost                     1.57.0                        0  
cmake                     3.0.1                         0  
dolfin                    1.5.0                np19py27_1  
eigen3                    3.2.1                         0  
fastcache                 1.0.2                    py27_0  
fenics                    1.5.0                         0  
ffc                       1.5.0                np19py27_1  
fiat                      1.5.0                np19py27_1  
instant                   1.5.0                np19py27_1  
mkl                       11.1                np19py27_p3  
mkl-rt                    11.1                         p0  
mkl-service               1.0.0                   py27_p1  
mpi4py                    1.3                      py27_0  
mpich2                    1.4.1p1                       0  
nose                      1.3.4                    py27_1  
numexpr                   2.3.1               np19py27_p0  [mkl]
numpy                     1.9.2                   py27_p0  [mkl]
openssl                   1.0.1k                        1  
pcre                      8.31                          0  
petsc                     3.5.2                    py27_1  
petsc4py                  3.5.1                    py27_1  
ply                       3.4                      py27_0  
python                    2.7.7                         2  
qt                        4.8.5                         0  
readline                  6.2                           2  
scikit-learn              0.15.2              np19py27_p0  [mkl]
scipy                     0.15.1              np19py27_p0  [mkl]
six                       1.9.0                    py27_0  
sqlite                    3.8.4.1                       1  
swig                      3.0.2                         0  
sympy                     0.7.6                    py27_0  
system                    5.8                           2  
tk                        8.5.18                        0  
ufl                       1.5.0                    py27_1  
vtk                       5.10.1                   py27_1  
zlib                      1.2.8                         0  
And if I start python and try to import dolfin I get:

> > > import dolfin
> > > Vendor:  Continuum Analytics, Inc.
> > > Package: mkl
> > > Message: trial mode expires in 30 days

---

DOLFIN runtime dependency is not met.
Install the following python module: 'ffc' 

## and make sure its location is listed in PYTHONPATH.

I get this message even after adding the anaconda/envs/fenics27 path to PYTHONPATH.

**Comment by astrojuanlu** [comment]
We're making progress then! What happens if you try to import ffc directly?

**Comment by astrojuanlu** [comment]
Hello @bcrestel, any progress with this?

**Comment by astrojuanlu** [comment]
Closing this, feel free to reopen if error persists.

**Comment by bcrestel** [comment]
Sorry, we went a different route. Thanks for your help.
