### ISSUE TITLE
Problem with petsc4py?

### ISSUE THREAD

**Issue by quang-ha** [Juanlu001/fenics-recipes#52]
Was helping my friend installing `fenics` using `conda` packages. When we came across `petsc4py` build, the following error comes up:

```
fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
```

Apparently for some reasons, `conda` does not have `numpy` header files in `include/python2.7/` but it is allocated in `lib/python2.7/site-packages/numpy/core/include/numpy` instead... 

Could well be a bug, but now as I was trying to install dolfin using these recipes on a new environment, this happens as well...

**Comment by mikaem** [comment]
Hi

Which platform is this? I have not seen this on my Ubuntu 15.04. I am starting a fresh anaconda, installing gcc and cmake and then dolfin dependencies with no problems. Have you tried to remove the 1.9 dependence of numpy from meta.yaml? The newest numpy in anaconda is 1.10...

M

**Comment by quang-ha** [comment]
My fresh `numpy` on `conda` is 1.10, so... still manage to flick through `dolfin` install without `petsc4py` anyway...

Platform wise, Ubuntu 14.04 LT3

**Comment by mikaem** [comment]
Ok, but are you removing "==1.9" from "numpy ==1.9" from meta.yaml when building petsc4py?

**Comment by quang-ha** [comment]
I changed it to `>=1.9` and it never asked `numpy` to downgrade.

**Comment by quang-ha** [comment]
Seems like the instruction to install with `conda` on the webpage `fenicsproject.org` would need to be updated as well.. I don't recall seeing `boost` here but that's a separate matter...

**Comment by mikaem** [comment]
Conda is a living breathing environment bound to fail from time to time. What's the issue with boost?

**Comment by quang-ha** [comment]
Just to point out that here the instruction still say `boost` :) http://fenicsproject.org/download/installation_using_conda.html#installation-using-conda while it should not anymore

**Comment by mikaem** [comment]
Ah, sure, boost from anaconda is ok now, no need to build it. But these things are changing rapidly. It was only a few months ago that anaconda swig was version 2 and too small to build dolfin...

**Comment by astrojuanlu** [comment]
Thanks a lot for taking care of this issue @mikaem, I didn't even have time to answer :)
