### ISSUE TITLE
ImportError: libgfortran.so.1

### ISSUE THREAD

**Issue by GitH00t** [Juanlu001/fenics-recipes#55]
Hello,
I am having issues importing dolfin
I followed the standard procedure using conda.
Ubuntu 15.10

```
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

I posted the results of 

```
$ conda info -a
$ conda list
$ which python
$ python ~/.anaconda3/envs/fenics27/share/dolfin/demo/documented/poisson/python/demo_poisson.py
```

[output](https://gist.github.com/GitH00t/9062fdb3122fa20ceab0)

When I upgrade numpy I can get rid of the problem stated above, but then run into

```
ImportError: libboost_system.so.1.57.0: cannot open shared object file: No such file or directory
```

Since you pointed out in the faq that this might be related to linking I executed the command you specified and posted it to this gist
[lbboutput](https://gist.github.com/GitH00t/c7f9c9bf7f3aab97e28a)
Unfortunately I am pretty newb at fenics and linux, so I don't really know what this is telling me.
I also tried to install boost 1.55.0 from your channel, but the error remained.

Thanks for the time!

Cheers

**Comment by GitH00t** [comment]
Hey, problem was actually very easy to solve, but since I am super new it was not so obvious.

I upgrade numpy to 1.10.4 and then installed boost 1.57 
Now I can run things normally. Issue can be closed.

**Comment by astrojuanlu** [comment]
Thanks @GitH00t, probably the instructions and dependencies should be updated.
