### ISSUE TITLE
Error using PETSc

### ISSUE THREAD

**Issue by e-aranda** [Juanlu001/fenics-recipes#59]
Hi, 

I am trying to use some PETSc functions and I have got an error which seems that something in the installation is wrong. The error:

PETSc/Mat.pyx in petsc4py.PETSc.Mat.multTranspose (src/petsc4py.PETSc.c:126588)()

Error: error code 60
[0] MatMultTranspose() line 2274 in /home/juanlu/miniconda/conda-bld/work/petsc-3.6.2/src/mat/interface/matrix.c

Note that the path which refers to PETSc  file is not in my computer.

Thanks,
Ernesto

**Comment by astrojuanlu** [comment]
This is a duplicate of https://github.com/Juanlu001/fenics-recipes/issues/28. I don't think the path in the traceback is affecting the error, please report it with the corresponding program to FEniCS developers and come back if it's my fault.

**Comment by e-aranda** [comment]
Sorry, you are right. It was my fault. The PETSc function is working fine.

Thank you
