### ISSUE TITLE
Unable to set up a conda environment to use FEniCS in

### ISSUE THREAD

**Issue by kdma-at-dtu** [Juanlu001/fenics-recipes#8]
@Juanlu001: I would like to create a conda environment to use FEniCS in. According to your instructions from https://github.com/Juanlu001/fenics-recipes/issues/1, I ran these commands:

$ conda create -n fenics27 python=2.7 ipython=2.2
$ source activate fenics27
(fenics27) $ conda install fenics --channel juanlu001

Unfortunately, after running the third command, I get:

Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/juanlu001/linux-64/eigen3-3.2.1-0.tar.bz2

May I ask you to help me set up a conda environment for FEniCS?

**Comment by astrojuanlu** [comment]
Hello @kdma-at-dtu, thanks for the report. This is my mistake because I screwed it up when uploading the packages (see https://github.com/Juanlu001/fenics-recipes/issues/2#issuecomment-78045015). I need to take the time to fix this properly, I will do this weekend.

In the meanwhile, install eigen3 from the `fenics:1.4.0:centos` channel:

```
(fenics27) $ conda install eigen3 --channel https://conda.binstar.org/juanlu001/channel/fenics:1.4.0:centos
```

**Comment by kdma-at-dtu** [comment]
I installed eigen3 as you suggested, and followed it with:

(fenics27) $ conda install fenics --channel juanlu001

The installation went through without problems. Thank you for the suggestion!

However, when I run the FEniCS tutorial script d1_p2D.py, I get an ImportError pointing towards:

from dolfin import *

The further elaboration on this error is as follows:

ImportError: libboost_filesystem.so.1.55.0: cannot open shared object file: No such file or directory

I noticed on https://github.com/Juanlu001/fenics-recipes/issues/2#issuecomment-78045015 that @oliveirarodolfo was able to resolve his issue with the boost-1.55.0-1 package, but I am not sure if this is directly related to my situation.

Could you let me know how I might go about handling my problem?

**Comment by astrojuanlu** [comment]
Can you post the output of `conda list`? I think I didn't specify correctly the required boost version (see #6) and perhaps you have the wrong version installed.

You should be able to install the correct boost version with:

```
(fenics 27) $ conda install "boost=1.55" --channel juanlu001
```

**Comment by kdma-at-dtu** [comment]
Thank you again for your feedback.

After installing "boost=1.55", I ran:

conda list

and got the following output:

```
#
binstar                   0.10.3                   py27_0  
boost                     1.55.0                        1  
clyent                    0.3.4                    py27_0  
cmake                     3.0.1                         0  
dolfin                    1.5.0                np19py27_1  
eigen3                    3.2.1                         0  
fastcache                 1.0.2                    py27_0  
fenics                    1.5.0                         0  
ffc                       1.5.0                np19py27_1  
fiat                      1.5.0                np19py27_1  
fontconfig                2.11.1                        2  
freetype                  2.5.2                         0  
instant                   1.5.0                np19py27_1  
ipython                   2.2.0                    py27_0  
libpng                    1.5.13                        1  
libxml2                   2.9.0                         0  
mkl                       11.1                np19py27_p3  
mkl-rt                    11.1                         p0  
mkl-service               1.0.0                   py27_p1  
mpi4py                    1.3                      py27_0  
mpich2                    1.4.1p1                       0  
nose                      1.3.4                    py27_1  
numexpr                   2.3.1                np19py27_0  
numpy                     1.9.2                    py27_0  
openssl                   1.0.1k                        1  
pcre                      8.31                          0  
petsc                     3.5.2                    py27_1  
petsc4py                  3.5.1                    py27_1  
pip                       6.1.1                    py27_0  
ply                       3.4                      py27_0  
python                    2.7.9                         2  
python-dateutil           2.4.2                    py27_0  
pytz                      2015.2                   py27_0  
pyyaml                    3.11                     py27_0  
qt                        4.8.6                         0  
readline                  6.2                           2  
requests                  2.6.0                    py27_0  
scikit-learn              0.15.2               np19py27_0  
scipy                     0.15.1               np19py27_0  
setuptools                15.0                     py27_0  
six                       1.9.0                    py27_0  
sphinx                    1.2.3                     <pip>
sqlite                    3.8.4.1                       1  
swig                      3.0.2                         0  
sympy                     0.7.6                    py27_0  
system                    5.8                           2  
tk                        8.5.18                        0  
ufl                       1.5.0                    py27_1  
vtk                       5.10.1                   py27_1  
yaml                      0.1.4                         0  
zlib                      1.2.8                         0  `
```

Unfortunately, when I now run the FEniCS tutorial script d1_p2D.py, the following is shown:

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/marinov/anaconda3/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/_common.so)

Do you think you could help me resolve this as well?

**Comment by astrojuanlu** [comment]
This perhaps means your system is too old. Can you tell which is your Linux distribution, and version? In this case you will have to use the packages from the `fenics:1.4.0:centos` channel as specified here:

http://fenicsproject.org/download/installation_using_conda.html#installation-using-conda

**Comment by kdma-at-dtu** [comment]
My operating system is a 64-bit Ubuntu 14.04 LTS. Could you confirm if this indeed means that my system is too old?

**Comment by astrojuanlu** [comment]
I was surprised to see it is indeed too old for these packages but I realized the core devs provide binaries of FEniCS 1.5 for 14.04 too, which means I can probably manage to recompile 1.5 to make it compatible with your distro. I won't be able to do it until this weekend, so you can either wait or use the 1.4.0 packages in the meanwhile.

**Comment by kdma-at-dtu** [comment]
Thank you for all your attention and prompt feedback. Could you let me know when you have had a chance to recompile FEniCS 1.5 to make it compatible with Ubuntu 14.04 LTS?

**Comment by astrojuanlu** [comment]
Sure, I will ping you in this same issue! :)

**Comment by kdma-at-dtu** [comment]
Thank you!

**Comment by porphyrius** [comment]
Hi Juanlu,

I upgraded to ubuntu 15.04 and fenics stopped functioning, so I did
rm -fr anaconda
and reinstalled it.

Now I am reinstalling fenics using your fenics recipe, and I get the same as kdma-at-dtu:

conda install fenics mkl --channel juanlu001

Fetching packages ...
Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/juanlu001/linux-64/eigen3-3.2.1-0.tar.bz2

however, the alternative channel doesn't work either:

conda install eigen3 --channel https://conda.binstar.org/juanlu001/channel/fenics:1.4.0:centos
Fetching package metadata: ......
Error: No packages found in current linux-64 channels matching: eigen3

Can you possibly help me?

Andrea

**Comment by astrojuanlu** [comment]
Hello @porphyrius, thanks for the comment and sorry for the delay. The problem you describe is now being tracked at #17.

**Comment by astrojuanlu** [comment]
Closing this issue in favor of #9, I plan to solve this probably this week.

**Comment by archwndas** [comment]
Dear Juan,

There is a problem installing on an older system.

```
$ conda install fenics mkl --channel juanlu001
```

I get the error

```
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days


DOLFIN runtime dependency is not met.
Install the following python module: 'ffc'
and make sure its location is listed in PYTHONPATH.
```

However, PYTHONPATH points to the correct directory. For example running `ls $PYTHONPATH` shows all the install packages (ufc, ufl, ffc etc.)

```
$ echo $PYTHONPATH
/users/archwn/anaconda/lib/python2.7/site-packages
```

running ffc I get 

```
$ffc
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found
```

Which means, that for compatibility you need to compile on a linux64 system with a very old glibc.

```
$ ldd --version
ldd (GNU libc) 2.11.3
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

On Ubuntu 15.04

```
$ ldd --version
ldd (Ubuntu GLIBC 2.21-0ubuntu4) 2.21
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by archwndas** [comment]
Dear Juan,

It would be nice if you could also provide with FEniCS the packages:
1. slepc
2. slepc4py

These are constantly missing but they are essential for eigenvalue problems where you want to choose your linear solver of choice and not the default one which is terribly slow.

**Comment by archwndas** [comment]
Dear Juan,
Installed anaconda in Ubuntu 15.04. Then FEniCS. Trying to run the very simple poisson demo I got the error:

```
$ python demo_poisson.py
Calling FFC just-in-time (JIT) compiler, this may take some time.
In instant.recompile: The module did not compile with command 'make VERBOSE=1', see '/home/archwn/.instant/error/ffc_form_746ebe8521dc9d314e6f65075dbc60d03cfee94b/compile.log'
Traceback (most recent call last):
    File "demo_poisson.py", line 41, in <module>
        V = FunctionSpace(mesh, "Lagrange", 1)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/dolfin/functions/functionspace.py", line 468, in __init__
        FunctionSpaceBase.__init__(self, mesh, element, constrained_domain)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/dolfin/functions/functionspace.py", line 153, in __init__
        ufc_element, ufc_dofmap = jit(self._ufl_element, mpi_comm=mesh.mpi_comm())
      File "/home/archwn/anaconda/lib/python2.7/site-packages/dolfin/compilemodules/jit.py", line 64, in mpi_jit
        return local_jit(*args, **kwargs)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/dolfin/compilemodules/jit.py", line 128, in jit
        return form_compiler.jit(form, parameters=p)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/ffc/jitcompiler.py", line 72, in jit
        return jit_element(ufl_object, parameters)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/ffc/jitcompiler.py", line 177, in jit_element
        compiled_form, module, prefix = jit_form(form, parameters)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/ffc/jitcompiler.py", line 148, in jit_form
        cache_dir = cache_dir)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/ffc/backends/ufc/build.py", line 73, in build_ufc_module
        **kwargs)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/instant/build.py", line 563, in build_module
        recompile(modulename, module_path, new_compilation_checksum, build_system)
      File "/home/archwn/anaconda/lib/python2.7/site-packages/instant/build.py", line 165, in recompile
        instant_error(msg % (cmd, compile_log_filename_dest))
      File "/home/archwn/anaconda/lib/python2.7/site-packages/instant/output.py", line 85, in instant_error
        raise RuntimeError(text)
    RuntimeError: In instant.recompile: The module did not compile with command 'make VERBOSE=1', see '/home/archwn/.instant/error/ffc_form_746ebe8521dc9d314e6f65075dbc60d03cfee94b/compile.log'
```

**Comment by astrojuanlu** [comment]
Dear @archwndas,

The issue you point out in https://github.com/Juanlu001/fenics-recipes/issues/8#issuecomment-112367224 is due to the fact that you need to install FEniCS 1.4.0, as explained in http://fenicsproject.org/download/installation_using_conda.html#importerror-lib64-libc-so-6-version-glibc-2-14-not-found.

The second issue https://github.com/Juanlu001/fenics-recipes/issues/8#issuecomment-112371241 is unexpected though, do you care to report a new issue so we can start looking at it?

**Comment by astrojuanlu** [comment]
@kdma-at-dtu I just recompiled FEniCS 1.5.0 in Ubuntu 14.04, please ping me if you give it a try :)
